package frame;

import controller.ControllerAnggota;
import data.DataAnggota;
import data.DataPembayaran;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Aodi
 */
public class EditAnggota extends javax.swing.JFrame {

    private ControllerAnggota controllerAnggota = new ControllerAnggota();

    int idAnggota;

    String nama,
            jenis_kelamin,
            email,
            noHP,
            paket,
            coach,
            statusPembayaran,
            statusKeanggotaan,
            tanggalPembayaran,
            tenggatPembayaran;

    /**
     * Creates new form Edit
     *
     * @param id
     */
    public EditAnggota(int id) {
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);

        initComponents();

        DataAnggota dataAnggota = controllerAnggota.getDataByID(id);

        this.idAnggota = id;

        fieldNama.setText(dataAnggota.getNama());
        fieldEmail.setText(dataAnggota.getEmail());
        fieldNoHP.setText(dataAnggota.getNoHP());
        areaStatusPembayaran.setText(dataAnggota.getStatusPembayaran());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opsiJenisKelamin = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        fieldNoHP = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        comboboxPaket = new javax.swing.JComboBox<>();
        comboboxCoach = new javax.swing.JComboBox<>();
        opsiLakiLaki = new javax.swing.JRadioButton();
        opsiPerempuan = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        simpanButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaStatusPembayaran = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FitSport");
        setName(""); // NOI18N
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Nama");

        jLabel4.setText("Email");

        jLabel6.setText("No HP");

        jLabel7.setText("Paket");

        jLabel8.setText("Coach");

        jLabel5.setText("Jenis Kelamin");

        comboboxPaket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silver", "Gold", "Platinum" }));

        comboboxCoach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alex Johnson", "Jessica Martinez", "Brian Wilson", "Emily Turner", "David Miller", "Tanpa Coach" }));

        opsiJenisKelamin.add(opsiLakiLaki);
        opsiLakiLaki.setText("Laki - Laki");

        opsiJenisKelamin.add(opsiPerempuan);
        opsiPerempuan.setText("Perempuan");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FitSport");

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Status Pembayaran");

        areaStatusPembayaran.setColumns(20);
        areaStatusPembayaran.setRows(5);
        jScrollPane3.setViewportView(areaStatusPembayaran);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(opsiLakiLaki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(opsiPerempuan))
                            .addComponent(jLabel4)
                            .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(simpanButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboboxPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(comboboxCoach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNoHP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxCoach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opsiPerempuan)
                    .addComponent(opsiLakiLaki))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
        nama = fieldNama.getText();
        email = fieldEmail.getText();
        noHP = fieldNoHP.getText();
        paket = comboboxPaket.getItemAt(comboboxPaket.getSelectedIndex());
        coach = comboboxCoach.getItemAt(comboboxCoach.getSelectedIndex());
        statusPembayaran = areaStatusPembayaran.getText();

        // Validasi Nama
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi Email
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi Nomor HP
        if (noHP.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nomor HP tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi Paket
        if (paket.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih paket terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi Coach
        if (coach.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih coach terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; // Hentikan proses jika validasi gagal
        }

        // Validasi Status Pembayaran
        if (statusPembayaran.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Status pembayaran tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi Jenis Kelamin
        if (opsiLakiLaki.isSelected()) {
            jenis_kelamin = opsiLakiLaki.getText();
        } else if (opsiPerempuan.isSelected()) {
            jenis_kelamin = opsiPerempuan.getText();
        } else {
            JOptionPane.showMessageDialog(null, "Jenis kelamin tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi apakah statusPembayaran hanya boleh "Belum Bayar" atau "Sudah Bayar"
        if (!"Belum Bayar".equalsIgnoreCase(statusPembayaran) && !"Sudah Bayar".equalsIgnoreCase(statusPembayaran)) {
            JOptionPane.showMessageDialog(this, "Status pembayaran hanya boleh 'Belum Bayar' atau 'Sudah Bayar'", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi Status Keanggotaan
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalSekarang = sdf.format(new Date());
        int dataHari = 30;

        DataPembayaran dataPembayaran = new DataPembayaran(statusPembayaran, null, tanggalSekarang, null);
        PendaftaranAnggota pendaftaranAngota = new PendaftaranAnggota();

        pendaftaranAngota.menentukanStatusKeanggotaan(dataPembayaran, dataHari);

        statusPembayaran = dataPembayaran.getStatusPembayaran();
        statusKeanggotaan = dataPembayaran.getStatusKeanggotaan();
        tanggalPembayaran = dataPembayaran.getTanggalPembayaran();
        tenggatPembayaran = dataPembayaran.getTenggatPembayaran();

        int konfirmasi = JOptionPane.showConfirmDialog(
                null,
                "Apakah data sudah lengkap?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        switch (konfirmasi) {
            case JOptionPane.YES_OPTION -> {
                controllerAnggota.updateDataByID(idAnggota, nama, jenis_kelamin, email, noHP, paket, coach, statusPembayaran, statusKeanggotaan, tanggalPembayaran, tenggatPembayaran);
                dispose();
            }
            case JOptionPane.NO_OPTION ->
                JOptionPane.showMessageDialog(null, "Mohon isi data hingga lengkap!", "Peringatan", JOptionPane.CANCEL_OPTION);
        }

    }//GEN-LAST:event_simpanButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaStatusPembayaran;
    private javax.swing.JComboBox<String> comboboxCoach;
    private javax.swing.JComboBox<String> comboboxPaket;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldNoHP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.ButtonGroup opsiJenisKelamin;
    private javax.swing.JRadioButton opsiLakiLaki;
    private javax.swing.JRadioButton opsiPerempuan;
    private javax.swing.JButton simpanButton;
    // End of variables declaration//GEN-END:variables

}
